//! CPLEX LP-compatible text frontend.
//!
//! The parser is allocation-conscious: tokens are borrowed slices into the
//! input buffer, names are interned by a hash table, and only semantic arrays
//! survive `finish`. Expressions are parsed directly without constructing an
//! AST.

const std = @import("std");
const types = @import("../types.zig");
const Builder = @import("../builder.zig").Builder;
const ModelData = @import("../model_data.zig").ModelData;
const output = @import("../output.zig");

const Section = enum { none, objective, constraints, bounds, binaries, generals, semicont, semiint, end };

const Parser = struct {
    allocator: std.mem.Allocator,
    builder: Builder,
    variables: std.StringHashMap(usize),
    pending_objective_coefficient: ?f64 = null,
    objective_sign: f64 = 1.0,

    fn init(allocator: std.mem.Allocator, name: []const u8) Parser {
        var builder = Builder.init(allocator);
        builder.name = name;
        return .{ .allocator = allocator, .builder = builder, .variables = std.StringHashMap(usize).init(allocator) };
    }

    fn deinit(self: *Parser) void {
        self.variables.deinit();
        self.builder.deinit();
    }

    fn variable(self: *Parser, name: []const u8) types.IoError!usize {
        if (!validName(name)) return error.InvalidName;
        if (self.variables.get(name)) |index| return index;
        const index = try self.builder.addColumn(.{ .name = name });
        self.variables.put(name, index) catch return error.OutOfMemory;
        return index;
    }
};

pub fn parse(allocator: std.mem.Allocator, input: []const u8, model_name: []const u8, options: types.ReadOptions) types.IoError!ModelData {
    var parser = Parser.init(allocator, model_name);
    defer parser.deinit();
    var section: Section = .none;
    var saw_objective = false;
    var saw_end = false;
    var lines = std.mem.tokenizeScalar(u8, input, '\n');
    while (lines.next()) |raw| {
        const code = if (std.mem.indexOfScalar(u8, raw, '\\')) |at| raw[0..at] else raw;
        const line = std.mem.trim(u8, code, " \t\r");
        if (line.len == 0) continue;
        if (header(line)) |next| {
            if (section == .objective and next.section != .objective) {
                if (parser.pending_objective_coefficient) |constant| {
                    parser.builder.objective_offset += constant;
                    parser.pending_objective_coefficient = null;
                }
            }
            section = next.section;
            if (next.sense) |sense| {
                parser.builder.objective_sense = sense;
                saw_objective = true;
            }
            if (section == .end) saw_end = true;
            continue;
        }
        switch (section) {
            .objective => try parseObjective(&parser, line),
            .constraints => try parseConstraint(&parser, line),
            .bounds => try parseBound(&parser, line),
            .binaries => try parseTypes(&parser, line, .binary),
            .generals => try parseTypes(&parser, line, .integer),
            .semicont => try parseTypes(&parser, line, .semi_continuous),
            .semiint => try parseTypes(&parser, line, .semi_integer),
            else => return error.InvalidSyntax,
        }
    }
    if (!saw_objective or !saw_end) return error.InvalidSyntax;
    return parser.builder.finish(options);
}

pub fn write(file: *std.Io.Writer, allocator: std.mem.Allocator, model: types.ModelView, names: output.Names, options: types.WriteOptions) types.IoError!void {
    _ = options;
    for (names.columns) |name| if (!validName(name)) return error.InvalidName;
    for (names.rows) |name| if (!validName(name)) return error.InvalidName;
    try output.write(file, "\\ LP format generated by zhighs\n");
    try output.write(file, if (model.objective_sense == .minimize) "Minimize\n obj:" else "Maximize\n obj:");
    var first = true;
    for (model.col_cost, names.columns) |coefficient, name| try writeTerm(file, allocator, coefficient, name, &first);
    if (model.objective_offset != 0.0) {
        if (first)
            try output.print(file, allocator, " {d}", .{model.objective_offset})
        else if (model.objective_offset < 0.0)
            try output.print(file, allocator, " - {d}", .{@abs(model.objective_offset)})
        else
            try output.print(file, allocator, " + {d}", .{model.objective_offset});
        first = false;
    }
    if (first) try output.write(file, " 0");
    try output.write(file, "\nSubject To\n");

    const row_starts = allocator.alloc(usize, model.numRows() + 1) catch return error.OutOfMemory;
    defer allocator.free(row_starts);
    @memset(row_starts, 0);
    for (model.matrix.row_indices) |row| row_starts[row.toUsize() + 1] += 1;
    for (0..model.numRows()) |row| row_starts[row + 1] += row_starts[row];
    const row_columns = allocator.alloc(usize, model.matrix.nnz()) catch return error.OutOfMemory;
    defer allocator.free(row_columns);
    const row_values = allocator.alloc(f64, model.matrix.nnz()) catch return error.OutOfMemory;
    defer allocator.free(row_values);
    const cursor = allocator.dupe(usize, row_starts[0..model.numRows()]) catch return error.OutOfMemory;
    defer allocator.free(cursor);
    for (0..model.numCols()) |column| {
        for (model.matrix.col_starts[column]..model.matrix.col_starts[column + 1]) |position| {
            const row = model.matrix.row_indices[position].toUsize();
            const destination = cursor[row];
            cursor[row] += 1;
            row_columns[destination] = column;
            row_values[destination] = model.matrix.values[position];
        }
    }
    for (0..model.numRows()) |row| {
        try output.print(file, allocator, " {s}:", .{names.rows[row]});
        const lower = model.row_lower[row];
        const upper = model.row_upper[row];
        const ranged = !std.math.isInf(lower) and !std.math.isInf(upper) and lower != upper;
        if (ranged) try output.print(file, allocator, " {d} <=", .{lower});
        first = true;
        for (row_starts[row]..row_starts[row + 1]) |position| try writeTerm(file, allocator, row_values[position], names.columns[row_columns[position]], &first);
        if (first) try output.write(file, " 0");
        if (lower == upper)
            try output.print(file, allocator, " = {d}\n", .{lower})
        else if (std.math.isInf(lower))
            try output.print(file, allocator, " <= {d}\n", .{upper})
        else if (std.math.isInf(upper))
            try output.print(file, allocator, " >= {d}\n", .{lower})
        else
            try output.print(file, allocator, " <= {d}\n", .{upper});
    }
    try output.write(file, "Bounds\n");
    for (0..model.numCols()) |column| try writeBound(file, allocator, names.columns[column], model.col_lower[column], model.col_upper[column]);
    try writeTypes(file, allocator, model, names.columns, .binary, "Binaries");
    try writeTypes(file, allocator, model, names.columns, .integer, "Generals");
    try writeTypes(file, allocator, model, names.columns, .semi_continuous, "Semi-Continuous");
    try writeTypes(file, allocator, model, names.columns, .semi_integer, "Semi-Integer");
    try output.write(file, "End\n");
}

fn writeTerm(file: *std.Io.Writer, allocator: std.mem.Allocator, coefficient: f64, name: []const u8, first: *bool) types.IoError!void {
    if (coefficient == 0.0) return;
    if (!std.math.isFinite(coefficient)) return error.NonFiniteValue;
    if (first.*) try output.write(file, if (coefficient < 0.0) " - " else " ") else try output.write(file, if (coefficient < 0.0) " - " else " + ");
    const magnitude = @abs(coefficient);
    if (magnitude != 1.0) try output.print(file, allocator, "{d} ", .{magnitude});
    try output.write(file, name);
    first.* = false;
}

fn writeBound(file: *std.Io.Writer, allocator: std.mem.Allocator, name: []const u8, lower: f64, upper: f64) types.IoError!void {
    if (std.math.isNan(lower) or std.math.isNan(upper) or lower > upper) return error.InvalidBounds;
    if (std.math.isInf(lower) and lower < 0 and std.math.isInf(upper) and upper > 0)
        try output.print(file, allocator, " {s} free\n", .{name})
    else if (lower == upper)
        try output.print(file, allocator, " {s} = {d}\n", .{ name, lower })
    else if (!std.math.isInf(lower) and !std.math.isInf(upper))
        try output.print(file, allocator, " {d} <= {s} <= {d}\n", .{ lower, name, upper })
    else if (!std.math.isInf(lower))
        try output.print(file, allocator, " {s} >= {d}\n", .{ name, lower })
    else
        try output.print(file, allocator, " {s} <= {d}\n", .{ name, upper });
}

fn writeTypes(file: *std.Io.Writer, allocator: std.mem.Allocator, model: types.ModelView, names: []const []u8, kind: types.VariableType, title: []const u8) types.IoError!void {
    var any = false;
    for (model.col_type) |actual| if (actual == kind) {
        any = true;
        break;
    };
    if (!any) return;
    try output.print(file, allocator, "{s}\n", .{title});
    for (model.col_type, names) |actual, name| if (actual == kind) try output.print(file, allocator, " {s}\n", .{name});
}

const Header = struct { section: Section, sense: ?types.ObjectiveSense = null };

fn header(line: []const u8) ?Header {
    if (equalsAny(line, &.{ "minimize", "minimum", "min" })) return .{ .section = .objective, .sense = .minimize };
    if (equalsAny(line, &.{ "maximize", "maximum", "max" })) return .{ .section = .objective, .sense = .maximize };
    if (equalsAny(line, &.{ "subject to", "such that", "st", "s.t." })) return .{ .section = .constraints };
    if (std.ascii.eqlIgnoreCase(line, "bounds")) return .{ .section = .bounds };
    if (equalsAny(line, &.{ "binary", "binaries", "bin" })) return .{ .section = .binaries };
    if (equalsAny(line, &.{ "general", "generals", "gen" })) return .{ .section = .generals };
    if (equalsAny(line, &.{ "semi-continuous", "semis", "semi" })) return .{ .section = .semicont };
    if (std.ascii.eqlIgnoreCase(line, "semi-integer")) return .{ .section = .semiint };
    if (std.ascii.eqlIgnoreCase(line, "end")) return .{ .section = .end };
    return null;
}

fn equalsAny(value: []const u8, candidates: []const []const u8) bool {
    for (candidates) |candidate| if (std.ascii.eqlIgnoreCase(value, candidate)) return true;
    return false;
}

fn validName(name: []const u8) bool {
    if (name.len == 0 or name.len > 255 or std.ascii.isDigit(name[0])) return false;
    if (std.mem.indexOfScalar(u8, "<>=()[],", name[0]) != null) return false;
    for (name) |char| if (std.ascii.isWhitespace(char) or std.mem.indexOfScalar(u8, "+-*^:\\", char) != null) return false;
    const reserved = [_][]const u8{ "min", "minimum", "minimize", "max", "maximum", "maximize", "st", "bounds", "binary", "binaries", "general", "generals", "end", "free" };
    for (reserved) |word| if (std.ascii.eqlIgnoreCase(name, word)) return false;
    return true;
}

fn tokenize(allocator: std.mem.Allocator, text: []const u8) types.IoError!std.ArrayListUnmanaged([]const u8) {
    var result: std.ArrayListUnmanaged([]const u8) = .empty;
    errdefer result.deinit(allocator);
    var iterator = std.mem.tokenizeAny(u8, text, " \t\r");
    while (iterator.next()) |token| result.append(allocator, token) catch return error.OutOfMemory;
    return result;
}

fn parseFinite(text: []const u8) types.IoError!f64 {
    const value = std.fmt.parseFloat(f64, text) catch return error.InvalidNumber;
    if (!std.math.isFinite(value)) return error.NonFiniteValue;
    return value;
}

fn parseObjective(parser: *Parser, line: []const u8) types.IoError!void {
    var expression = line;
    if (std.mem.indexOfScalar(u8, expression, ':')) |colon| expression = std.mem.trimStart(u8, expression[colon + 1 ..], " \t");
    var tokens = try tokenize(parser.allocator, expression);
    defer tokens.deinit(parser.allocator);
    var index: usize = 0;
    if (parser.pending_objective_coefficient) |coefficient| {
        if (tokens.items.len == 0) return;
        const column = try parser.variable(tokens.items[0]);
        parser.builder.columns.items[column].cost += coefficient;
        parser.pending_objective_coefficient = null;
        index = 1;
    }
    while (index < tokens.items.len) {
        const token = tokens.items[index];
        if (std.mem.eql(u8, token, "+")) {
            parser.objective_sign = 1.0;
            index += 1;
            continue;
        }
        if (std.mem.eql(u8, token, "-")) {
            parser.objective_sign = -1.0;
            index += 1;
            continue;
        }
        if (std.fmt.parseFloat(f64, token)) |number| {
            if (!std.math.isFinite(number)) return error.NonFiniteValue;
            const coefficient = parser.objective_sign * number;
            parser.objective_sign = 1.0;
            if (index + 1 == tokens.items.len) {
                parser.pending_objective_coefficient = coefficient;
                return;
            }
            const column = try parser.variable(tokens.items[index + 1]);
            parser.builder.columns.items[column].cost += coefficient;
            index += 2;
        } else |_| {
            const column = try parser.variable(token);
            parser.builder.columns.items[column].cost += parser.objective_sign;
            parser.objective_sign = 1.0;
            index += 1;
        }
    }
}

fn parseConstraint(parser: *Parser, line: []const u8) types.IoError!void {
    var tokens = try tokenize(parser.allocator, line);
    defer tokens.deinit(parser.allocator);
    if (tokens.items.len < 3) return error.InvalidSyntax;
    var begin: usize = 0;
    var row_name: ?[]const u8 = null;
    if (std.mem.endsWith(u8, tokens.items[0], ":")) {
        row_name = tokens.items[0][0 .. tokens.items[0].len - 1];
        if (!validName(row_name.?)) return error.InvalidName;
        begin = 1;
    }
    var relation: ?usize = null;
    var second_relation: ?usize = null;
    for (tokens.items[begin..], begin..) |token, index| {
        if (std.mem.eql(u8, token, "<=") or std.mem.eql(u8, token, ">=") or std.mem.eql(u8, token, "=")) {
            if (relation == null) relation = index else {
                second_relation = index;
                break;
            }
        }
    }
    const at = relation orelse return error.InvalidSyntax;
    if (second_relation) |second| {
        if (at != begin + 1 or second + 2 != tokens.items.len or !std.mem.eql(u8, tokens.items[at], "<=") or !std.mem.eql(u8, tokens.items[second], "<=")) return error.InvalidSyntax;
        const lower = try parseFinite(tokens.items[begin]);
        const upper = try parseFinite(tokens.items[second + 1]);
        if (lower > upper) return error.InvalidBounds;
        const row = try parser.builder.addRow(.{ .name = row_name, .lower = lower, .upper = upper });
        try parseExpression(parser, tokens.items[at + 1 .. second], row);
        return;
    }
    if (at + 2 != tokens.items.len) return error.InvalidSyntax;
    const rhs = try parseFinite(tokens.items[at + 1]);
    const row = try parser.builder.addRow(if (std.mem.eql(u8, tokens.items[at], "<="))
        .{ .name = row_name, .upper = rhs }
    else if (std.mem.eql(u8, tokens.items[at], ">="))
        .{ .name = row_name, .lower = rhs }
    else
        .{ .name = row_name, .lower = rhs, .upper = rhs });
    try parseExpression(parser, tokens.items[begin..at], row);
}

fn parseExpression(parser: *Parser, tokens: []const []const u8, row: ?usize) types.IoError!void {
    var index: usize = 0;
    var sign: f64 = 1.0;
    while (index < tokens.len) {
        if (std.mem.eql(u8, tokens[index], "+")) {
            sign = 1.0;
            index += 1;
            continue;
        }
        if (std.mem.eql(u8, tokens[index], "-")) {
            sign = -1.0;
            index += 1;
            continue;
        }
        var coefficient: f64 = 1.0;
        var name = tokens[index];
        if (std.fmt.parseFloat(f64, tokens[index])) |number| {
            if (!std.math.isFinite(number)) return error.NonFiniteValue;
            if (index + 1 >= tokens.len) {
                if (number == 0.0) return;
                return error.UnsupportedFeature; // objective constants need an explicit constant term policy
            }
            coefficient = number;
            index += 1;
            name = tokens[index];
        } else |_| {}
        const column = try parser.variable(name);
        if (row) |row_index|
            try parser.builder.addTerm(row_index, column, sign * coefficient)
        else
            parser.builder.columns.items[column].cost += sign * coefficient;
        sign = 1.0;
        index += 1;
    }
}

fn parseBound(parser: *Parser, line: []const u8) types.IoError!void {
    var tokens = try tokenize(parser.allocator, line);
    defer tokens.deinit(parser.allocator);
    const values = tokens.items;
    if (values.len == 2 and std.ascii.eqlIgnoreCase(values[1], "free")) {
        const column = try parser.variable(values[0]);
        parser.builder.columns.items[column].lower = -std.math.inf(f64);
        parser.builder.columns.items[column].upper = std.math.inf(f64);
        return;
    }
    if (values.len == 3 and std.mem.eql(u8, values[1], "=")) {
        const column = try parser.variable(values[0]);
        const value = try parseFinite(values[2]);
        parser.builder.columns.items[column].lower = value;
        parser.builder.columns.items[column].upper = value;
        return;
    }
    if (values.len == 3 and (std.mem.eql(u8, values[1], ">=") or std.mem.eql(u8, values[1], "<="))) {
        const column = try parser.variable(values[0]);
        const value = try parseFinite(values[2]);
        if (std.mem.eql(u8, values[1], ">=")) parser.builder.columns.items[column].lower = value else parser.builder.columns.items[column].upper = value;
        return;
    }
    if (values.len == 5 and std.mem.eql(u8, values[1], "<=") and std.mem.eql(u8, values[3], "<=")) {
        const column = try parser.variable(values[2]);
        parser.builder.columns.items[column].lower = try parseFinite(values[0]);
        parser.builder.columns.items[column].upper = try parseFinite(values[4]);
        return;
    }
    return error.InvalidSyntax;
}

fn parseTypes(parser: *Parser, line: []const u8, kind: types.VariableType) types.IoError!void {
    var iterator = std.mem.tokenizeAny(u8, line, " \t\r");
    while (iterator.next()) |name| parser.builder.columns.items[try parser.variable(name)].kind = kind;
}

test "parses a linear mixed integer LP into canonical CSC" {
    const input =
        \\Maximize
        \\ obj: - 2 x + y
        \\Subject To
        \\ demand: 3 x - y >= -7
        \\Bounds
        \\ x <= 4
        \\ 0 <= y <= 1
        \\Binaries
        \\ y
        \\End
    ;
    var model = try parse(std.testing.allocator, input, "sample", .{});
    defer model.deinit();
    try std.testing.expectEqual(@as(usize, 2), model.col_cost.len);
    try std.testing.expectEqual(@as(usize, 1), model.row_lower.len);
    try std.testing.expectEqual(@as(usize, 2), model.matrix.nnz());
    try std.testing.expectEqual(types.VariableType.binary, model.col_type[1]);
    try std.testing.expectEqual(@as(f64, -2.0), model.col_cost[0]);
}
